
MYSQL_NAME = ''
MYSQL_USER = ''
MYSQL_PASSWORD = ''
MYSQL_HOST = ''
MYSQL_POST = ''

ALI_ACCESS_KEY_ID = ""
ALI_ACCESS_KEY_SECRET = ""
ALI_SIGN_NAME = ""
ALI_TEMPLATE_CODE = ""

QINIU_ACCESS_KEY = ''
QINIU_SECRET_KEY = ''
QINIU_BUCKET_NAME = ''
QINIU_DOMAIN = ''

BAIDU_CLOUD_USER_ID = ""
BAIDU_CLOUD_USER_KEY = ''

PAY_TOKEN = ''
PAY_UID = ''
